### PR TITLE
country selector should be empty by default to avoid user error

### PR DESCRIPTION
**Pull request by ianare**
if the user is not careful the country will be set incorrectly to the first in the list alphabetically

### CODE REVIEW

**Comment by henri-hulski** [comment]
When you use primary_countries it could be intentionally to preselect the country. Specially if you use only one.
So maybe it's better to solve this in the view.

**Comment by ianare** [comment]
Good point, I put it in the form instead, is that better?

**Comment by henri-hulski** [comment]
Looks better, but I think we should make it optional e.g. by introducing a SHOP_DEFAULT_COUNTRY setting, which could be False to not select any country (your proposition) or an alpha2 code to preselect that country or True (the default) to select the first country in the list.

**Comment by ianare** [comment]
Agree on principle but I think that the default should really be False, this is the normal behavior for this type of web form.

**Comment by henri-hulski** [comment]
Agree, the only problem is that it will break current behavior. So at least it should be mentioned in the ChangeLog as breaking. 
If you go for this the logic should be implemented in get_country_list().

**Comment by ianare** [comment]
Done, let me know what you think. Also changed next version to 1.1.0 due to the breaking change.

**Comment by ianare** [comment]
I've updated the readme, OK for merge?

Thanks,

**Comment by henri-hulski** [comment]
Looks great! Just fix the two line notes and it should be ready.

**Comment by ianare** [comment]
Ah, I see your point now, thanks.

The 2 lines were updated.

**Comment by henri-hulski** [comment]
Thanks a bunch!

**Comment by ianare** [comment]
Great, thanks! Do you have an idea when you would release a new version?

**Comment by henri-hulski** [comment]
Yeah, something between 10 minutes and half an hour. :wink:

**Comment by henri-hulski** [comment]
cartridge_braintree 1.1.0 is released!

**Pull request merged**
