### PR TITLE
add debug logs to payment process

### PR DESCRIPTION
**Pull request by ianare**
Thanks much for this module.

I found the process a little hard to debug without logging, so I added some.

Hope you like it ;-)

### CODE REVIEW

**Comment by henri-hulski** [comment]
Great! Thanks a lot. 👍
Could you add it to the docs with a little explanation how it works. 
Ah and please remove .idea from .gitignore. This should go in the user's
 ~/.gitignore.

**Comment by ianare** [comment]
Done. I also changed the level for transaction failure to warning as it's not really an application error.

**Comment by ianare** [comment]
Anything else blocking the merge request?

Thanks,

**Review by henri-hulski — APPROVED** [review]
Looks good. Cannot test it at the moment, but I will merge it and after testing make a new release. 
Thanks a bunch!

**Pull request merged**
